first_blog/config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  resources :posts do
    resources :comments
  end

end

first_blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

first_blog/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy 

	self.per_page = 10
end

first_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def edit
	  @post = Post.find(params[:post_id])
	  # @comment = @post.comments.find(params[:post_id])
	end

	def update
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.update(comment_params)
	  if @comment.save
	  	redirect_to post_path(@post)
	  else
	  	render 'edit'
	  end
	end

	def create
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.create(comment_params)

	  redirect_to post_path(@post)
	end

	def destroy
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.find(params[:id])
	  @comment.destroy
	  redirect_to post_path(@post)

	end

	private

	def comment_params
	  params.require(:comment).permit(:comment_author, :comment)
	end

end

first_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
    @posts = Post.paginate(:page => params[:page], :per_page => 10)
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])

  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy

  	redirect_to root_path
  end

  private

  def post_params
  	params.require(:post).permit(:title, :body)
  end

end

first_blog/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

first_blog/app/helpers/comments_helper.rb
module CommentsHelper
end

first_blog/app/helpers/posts_helper.rb
module PostsHelper
end

first_blog/app/helpers/static_helper.rb
module StaticHelper
end

first_blog/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<div class="form">
<%= form_for ([@post, @post.comments.build]) do |f| %>
	<div class="form-group">
		<%= f.label :comment_author %>
		<%= f.text_field :comment_author, class: "form-control" %> <br>
	</div>
	<div class="form-group">
		<%= f.label :comment %>
		<%= f.text_area :comment, class: "form-control" %> <br>
	</div>
	<div class="form-group">
		<%= f.submit "Submit Comment", class: "btn btn-success" %>
	</div>
<% end %>

<%= link_to "Cancel", post_path(@post), class: "btn btn-danger" %>
</div>

first_blog/app/views/layouts/_form.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

first_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Erik's_Iron_Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Post", new_post_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>



</body>
</html>

first_blog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="form">
	<%= form_for @post do |f| %>
		<div class="form-group">
		 	<%= f.label :title %>
		 	<%= f.text_field :title, class: "form-control" %> <br>
	  </div> 	
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: "form-control" %> <br>
		</div>
		<div class="form-group">
			<%= f.submit "Submit Post", class: "btn btn-success" %>
		</div>	
	<% end %>
</div>

<br>
<br>
<%= link_to "Cancel", root_path %>

first_blog/app/views/posts/index.html.erb
<div class="container-fluid">
<h1 class="All">All Posts</h1>

	<% @posts.each do |post| %>
		<h2 class="title">
			<%= link_to post.title, post %>
		</h2>
		<h5>
			<strong><%= post.author %></strong>
			<p> <%= post.created_at.strftime("%B, %d, %Y") %></p>
		</h5>
		
		<p class="body">
			<%= post.body %>
		</p>
		<p class="comment">
			Comments: <%= post.comments.count %>
		</p>
	<% end %>		

<br>
<%= will_paginate @posts %>
<br>
<br>
</div>

first_blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="form">
	<%= form_for @post do |f| %>
		<div class="form-group">
		 	<%= f.label :title %>
		 	<%= f.text_field :title, class: "form-control" %> <br>
	  </div> 	
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: "form-control" %> <br>
		</div>
		<div class="form-group">
			<%= f.submit "Submit Post", class: "btn btn-success" %>
		</div>	
	<% end %>
</div>


<br>
<br>
<%= link_to "Cancel", posts_path, class: "btn btn-danger" %>

first_blog/app/views/posts/show.html.erb
<div class="container-fluid">
	<h1><%= @post.title %></h1>
	<h5><strong>Authored By: </strong><%= @post.author %></h5>
	<p><%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-primary" %> <%= link_to "Delete Post", post_path(@post),
																			method: :delete,
																			data: { confirm: "Are you sure?"}, class: "btn btn-danger" %> </p>
	<p><%= @post.body %></p>


	<br>

	<h4>All Comments</h4>
	<% @post.comments.each do |c| %>
		<h5><%= c.comment_author %></h5>
		<p><%= c.comment %></p>
		<p><%=  link_to "Edit comment", edit_post_comment_path(c.post, c), class: "btn btn-primary" %>
		<%= link_to "Delete Comment?", post_comment_path(c.post, c),
										  method: :delete,
										  data: { confirm: "Are You Sure?" }, class: "btn btn-danger" %></p>
	<% end %>
	<br>
	<br>
	<br>

	<h4>Post A New Comment</h4>

	<%= form_for ([@post, Comment.new]) do |f| %>
		<div class="form">
			<div class="form-group">
				<%= f.label :comment_author %>
				<%= f.text_field :comment_author, class: "form-control" %> <br>
			</div>
			<div class="form-group">
				<%= f.label :comment %>
				<%= f.text_area :comment, class: "form-control" %> <br>
			</div>
			<div class="form-group">
				<%= f.submit "Submit Comment", class: "btn btn-success" %>
			</div>
		</div>
	<% end %>
</div>

 