threedoMVC/config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  resources :todos do
    member do
      post 'toggle'
    end

  end

end

threedoMVC/app/models/todo.rb
class Todo < ActiveRecord::Base
  validates_presence_of :todo_item

  def self.incomplete?
    Todo.where(complete: false).any?
  end

end

threedoMVC/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

threedoMVC/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.create(todo_params)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
  end

  def destroy_all
    @todos_delete = Todo.where(complete: true)
    @todos_delete.destroy_all
  end

  def toggle_all
    @todos = Todo.all
    Todo.update_all(complete: Todo.incomplete?)
  end

  def toggle
    @todo = Todo.find(params[:id])
    @todo.toggle!(:complete)
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
  end


  private
  def todo_params
    params.require(:todo).permit(:todo_item)
  end
end

threedoMVC/app/helpers/application_helper.rb
module ApplicationHelper
end

threedoMVC/app/helpers/todos_helper.rb
module TodosHelper
end

threedoMVC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThreedoMVC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

threedoMVC/app/views/todos/_todo.html.erb
<li id=<%= "todo_#{todo.id}" %>>
  <div class="view">
      <%= form_for todo, url: toggle_todo_path(todo), method: :post, remote: true do |f| %>
        <%= f.check_box :complete, :class => 'toggle' %>
      <% end %>
    <a><%= todo.todo_item %></a>
    <%= form_for todo, method: :delete, remote: true do |f| %>
      <%= f.button "", :class => "destroy" %>
    <% end %>
  </div>
  <form>
    <input class="edit" value="">
  </form>
</li>

threedoMVC/app/views/todos/completed.js.erb
// $('#todo_<%= @todo.completed %>').remove()

threedoMVC/app/views/todos/create.js.erb
$('<%= j(render @todo) %>').appendTo('#todo-list');
$('#<%= "todo_#{@todo.id}" %>').find(".toggle").click(function(){
  $(this).parent().submit();
});
$('#new-todo').val('')

threedoMVC/app/views/todos/destroy.js.erb
$('#todo_<%= @todo.id %>').remove()

threedoMVC/app/views/todos/destroy_all.js.erb
<% @todos_delete.each do |todo| %>
  $('#<%= "todo_#{id}" %>').remove();
<% end %>

threedoMVC/app/views/todos/index.html.erb
<!doctype html>
    <section id="todoapp">
      <header id="header">
        <h1>todos</h1>
        <form action="/todos" method="POST" data-remote="true">
          <input id="new-todo" placeholder="What needs to be done?" name="todo[todo_item]" autofocus>
        </form>
      </header>
      <!-- This section should be hidden by default and shown when there are todos to display -->
      <section id="main">
        <form action="/todos/toggle_all" method="POST" data-remote="true">
          <input id="toggle-all" type="checkbox">
          <label for="toggle-all">Mark all as complete</label>
        </form>
        <ul id="todo-list">
          <%= render @todos %>
        </ul>
      </section>
      <!-- This footer should hidden by default and shown when there are todos -->
      <footer id="footer">
        <!-- This should be `0 items left` by default -->
        <span id="todo-count"><strong>0</strong> items left</span>
        <ul id="filters">
          <li>
            <a class="selected" href="#">All</a>
          </li>
          <li>
            <a href="/#">Active</a>
          </li>
          <li>
            <a href="/#">Completed</a>
          </li>
        </ul>
        <!-- Hidden if no completed items are left ↓ -->
        <form>
          <button id="clear-completed">Clear completed</button>
        </form>
      </footer>
    </section>
    <footer id="info">
      <p>Double-click to edit a todo</p>
      <!-- Change this out with your name and url ↓ -->
      <p>Created by <a href="http://todomvc.com">you</a></p>
      <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
    </footer>

threedoMVC/app/views/todos/toggle.js.erb
$('#<%= "todo_#{@todo.id}" %>').find(".toggle").prop("checked", <%= @todo.complete %>)

threedoMVC/app/views/todos/toggle_all.js.erb
<% todos.each do |todo| %>
  $('#<%= "todo_#{todo.id}" %>').find('.toggle').prop('checked', <%= todo.complete %>)
  $('#toggle-all').prop('checked', <%= todo.complete %>)
<% end %>