Iron_Roster_Rails/config/routes.rb
Rails.application.routes.draw do

  root 'people#index'

  resources :peopl

end

Iron_Roster_Rails/app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :subject
	validates_presence_of :name, :subject_id, :github_account
end

Iron_Roster_Rails/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :people
end

Iron_Roster_Rails/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
  	@people = Person.all
  end

  def show
  	@person = Person.find(params[:id])
  end

  def edit
  	@person = Person.find(params[:id])
  end

  def update
  	@person = Person.find(params[:id])

  	if @person.update(person_params)
  		redirect_to @person
  	else
  		render 'edit'
  	end
  end

  def new
  	@person = Person.new
  end

  def create
	@person = Person.new(person_params)
	if @person.save
		redirect_to root_path 		
	else
		render 'new'
	end
  end

  def destroy
  	@person = Person.find(params[:id])
  	@person.destroy

  	redirect_to root_path
  end

  private
  	def person_params
 	  params.require(:person).permit(:name, :subject, :github_account)
 	end
end

Iron_Roster_Rails/app/helpers/people_helper.rb
module PeopleHelper
end

Iron_Roster_Rails/app/views/layouts/_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.input :name, label: 'Your Name' %>
  <%= f.input :subject, label: 'Subject' %>
  <%= f.input :github_account, label: 'github_account' %>
  <%= f.button :submit %>
<% end %>

Iron_Roster_Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IronRosterRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<br>
<br>
<br>
<%= link_to "New Student", new_person_path %>

</body>
</html>

Iron_Roster_Rails/app/views/people/edit.html.erb
<h1>Edit Personal Information</h1>

<%= render 'layouts/form' %>

<%= link_to "Cancel", root_path %>

Iron_Roster_Rails/app/views/people/index.html.erb
<h1>The Iron Roster</h1>
<table>
	<tr>
		<th>Name</th>
		<th>Subject</th>
		<th>Github Account</th>
		<th>Edit</th>
		<th>Delete?</th>
	</tr>
	<% @people.each do |person| %>
		<tr>
			<td><%= link_to person.name, person %></td>
			<td><%= person.subject %></td>
			<td><%= person.github_account %></td>
			<td><%= link_to "Edit", edit_person_path(person)  %></td>
			<td><%= link_to "Delete Student?", person_path(person), 
											   method: :delete,
											   data: { confirm: "Are You Sure?" } %></td>
		</tr>
	<% end %>

</table>

Iron_Roster_Rails/app/views/people/new.html.erb
<h1>New Student</h1>

<%= render 'layouts/form' %>



<%= link_to "Cancel", root_path %>

Iron_Roster_Rails/app/views/people/show.html.erb
<h1><%= @person.name %></h1>

<h4>Subject: <%= @person.subject %></h4>
<h4>Github Account: <%= @person.github_account %></h4>


<%= link_to 'Back to Index', root_path %>